cabal-version:      3.0
name:               haskellc
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             oleg.icefield
maintainer:         oleg.icefield@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable haskellc
    import:           warnings
    main-is:          Main.hs
    other-modules:    CompilerOptionsParser
    build-depends:
        base ^>=4.20.2.0,
        optparse-applicative ^>=0.19.0.0,
        haskellc-lexer

    hs-source-dirs:   src
    default-language: GHC2024

test-suite haskellc-test
    import:           warnings
    default-language: GHC2024

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0
