name:                 haskellc
version:              0.1.0.0
visibility:           public
id:                   haskellc-0.1.0.0-inplace
key:                  haskellc-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           oleg.icefield@gmail.com
author:               oleg.icefield
category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/build

library-dirs:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/build

library-dirs-static:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/build

dynamic-library-dirs:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/build

data-dir:             /home/natalia/projects/haskellc/.
hs-libraries:         HShaskellc-0.1.0.0-inplace
depends:              base-4.20.2.0-f074
haddock-interfaces:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/doc/html/haskellc/haskellc.haddock

haddock-html:
    /home/natalia/projects/haskellc/dist-newstyle/build/x86_64-linux/ghc-9.10.3/haskellc-0.1.0.0/doc/html/haskellc
